name: Release Action

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies for Ubuntu
      - name: Install Gleam on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"

      # Install dependencies for macOS
      - name: Install Gleam on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install gleam

      # Install dependencies for Windows
      - name: Install Gleam on Windows         
        if: matrix.os == 'windows-latest'
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"

      - uses: actions/setup-node@v4
        name: Set up node
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
